### 회원가입(고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "2023-03-28",
  "email": "scratch@naver.com",
  "name": "string",
  "password": "string",
  "phone": "string"
}

### 이메일 인증(고객)
GET http://localhost:8081/signup/customer/verify?email=scratch@naver.com&code=RwsieFP1x9

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "scratch@naver.com",
  "password": "string"
}

### 회원정보조회
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpbS9zdXRYbS9YSnVRQmZMODdPK3MvMFlWZTV6c1FMRmM5L1BHOXFtRTBFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAyMzI2NzIsImV4cCI6MTY4MDMxOTA3Mn0.ZoJUyOk4zcd-5BlMGcWE9_LTsB_uKM8XZ3ymh0SJ0vA


### 잔액 변경(고객)
POST http://localhost:8081/customer/balance
Content-Type:application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpbS9zdXRYbS9YSnVRQmZMODdPK3MvMFlWZTV6c1FMRmM5L1BHOXFtRTBFPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAyMzIwNzQsImV4cCI6MTY4MDMxODQ3NH0.qOQEubDapdq4czgz4tKgwntBEHuSJs8rfeyndHF13II

{
  "from": "server",
  "message": "돈충전",
  "money": 50000
}

### 회원가입 (샐러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1979-12-02",
  "email": "wlals4253@gmail.com",
  "name": "string",
  "password": "ko",
  "phone": "010-0000-0000"
}


### 이메일 인증 (샐러)
GET http://localhost:8081/signup/seller/verify?email=wlals4253@gmail.com&code=07TdeJP8UN



### 로그인 (샐러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "wlals4253@gmail.com",
  "password": "ko"
}


### 회원 정보 조회 (샐러)
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


