### 프로덕트
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


{
  "description": "상품설명",
  "items": [
    {
      "count": 1,
      "name": "280",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}
### 프로덕트 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


    {
      "productId": 1,
      "count": 1,
      "name": "270",
      "price": 10000
    }
### 프로덕트 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


{
  "description": "상품설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}
### 프로덕트 아이템 수정
PUT  http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


{
  "id": 1,
  "count": 1,
  "name": "270",
  "price": 10000
}

### 프로덕트 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


### 프로덕트 아이템 삭제
DELETE  http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU



### 이메일 인증(고객)
GET http://localhost:8081/signup/customer/verify?email=scratch@naver.com&code=K0RCEWOwBn

### 회원정보조회
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpbS9zdXRYbS9YSnVRQmZMODdPK3MvMFlWZTV6c1FMRmM5L1BHOXFtRTBFPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAwMDAwOTMsImV4cCI6MTY4MDA4NjQ5M30.IpEXDxv-Yv4VGW1yuF9p7C8LPPBr28qwdK0lc5WUYvM



### 잔액 변경(고객)
POST http://localhost:8081/customer/balance
Content-Type:application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpbS9zdXRYbS9YSnVRQmZMODdPK3MvMFlWZTV6c1FMRmM5L1BHOXFtRTBFPSIsImp0aSI6InFpalNBakR1VUZRVnlabDFkMStsZ1E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAwMDAwOTMsImV4cCI6MTY4MDA4NjQ5M30.IpEXDxv-Yv4VGW1yuF9p7C8LPPBr28qwdK0lc5WUYvM

{
  "from": "server",
  "message": "돈충전",
  "money": 50000
}

### 회원가입 (샐러)
POST http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1979-12-02",
  "email": "wlals4253@gmail.com",
  "name": "string",
  "password": "ko",
  "phone": "010-0000-0000"
}


### 이메일 인증 (샐러)
GET http://localhost:8081/signup/seller/verify?email=wlals4253@gmail.com&code=hjKAlPh9UL



### 로그인 (샐러)
POST http://localhost:8081/signin/seller
Content-Type: application/json

{
  "email": "wlals4253@gmail.com",
  "password": "ko"
}


### 회원 정보 조회 (샐러)
GET http://localhost:8081/seller/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcWh0Y1BzZnV5TnhmS04xV05WZm43SCsrT1VMVmFHaHltWEZGSXRPZ3E0PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDM3MTg4LCJleHAiOjE2ODAxMjM1ODh9.CMms6PdNghhakJ-_KndBHyonI1DEUPq-wYBCbk58XdU


